"""
Django settings for control_panel project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

from __future__ import annotations

import os
from datetime import timedelta
from pathlib import Path


BASE_DIR = (
    Path(__file__)
    .resolve()
    .parent
    .parent
)


SECRET_KEY = (
    "django-insecure-"
    "gc+l&=u-n@wcsa4!yu_)og-+x+txr*uz&qz2&+b4qeq&53-u1b"
)


DEBUG = True


ALLOWED_HOSTS = []


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "operations",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = (
    "control_panel.urls"
)


TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends."
            "django.DjangoTemplates"
        ),
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template."
                    "context_processors.request"
                ),
                (
                    "django.contrib.auth."
                    "context_processors.auth"
                ),
                (
                    "django.contrib.messages."
                    "context_processors.messages"
                ),
            ],
        },
    },
]


WSGI_APPLICATION = (
    "control_panel.wsgi.application"
)


DATABASES = {
    "default": {
        "ENGINE": (
            "django.db.backends.sqlite3"
        ),
        "NAME": (
            BASE_DIR
            / "db.sqlite3"
        ),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "NumericPasswordValidator"
        ),
    },
]


LANGUAGE_CODE = (
    "en-us"
)


TIME_ZONE = (
    "UTC"
)


USE_I18N = True


USE_TZ = True


STATIC_URL = (
    "static/"
)


DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "scraper": {
            "format": (
                "%(asctime)s | "
                "%(levelname)-8s | "
                "%(message)s"
            ),
            "datefmt": "%H:%M:%S",
        },
    },

    "handlers": {
        "console": {
            "class": (
                "logging.StreamHandler"
            ),
            "formatter": (
                "scraper"
            ),
        },
    },

    "loggers": {
        "captcha_lab": {
            "handlers": [
                "console"
            ],
            "level": (
                "INFO"
            ),
            "propagate": False,
        },
    },
}


# ------------------------------------------------------------------
# Celery
# ------------------------------------------------------------------

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    "redis://127.0.0.1:6379/0",
)


CELERY_TASK_SERIALIZER = (
    "json"
)


CELERY_ACCEPT_CONTENT = [
    "json"
]


CELERY_RESULT_SERIALIZER = (
    "json"
)


CELERY_TIMEZONE = (
    "UTC"
)


CELERY_ENABLE_UTC = True


# ------------------------------------------------------------------
# Scheduled scraper
# ------------------------------------------------------------------

SCRAPER_SCHEDULE_MINUTES = int(
    os.getenv(
        "SCRAPER_SCHEDULE_MINUTES",
        "30",
    )
)


CELERY_BEAT_SCHEDULE = {
    "run-scheduled-scraper": {
        "task": (
            "operations."
            "run_scheduled_scraper"
        ),
        "schedule": timedelta(
            minutes=(
                SCRAPER_SCHEDULE_MINUTES
            )
        ),
    },
}
