# Generated by Django 5.2.17 on 2026-08-17 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('appointment_found', 'Appointment Found'), ('no_appointment', 'No Appointment'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('visa_sub_types', models.JSONField(blank=True, default=list)),
                ('appointment_visa_sub_type', models.CharField(blank=True, max_length=255)),
                ('page_url', models.URLField(blank=True, max_length=2000)),
                ('error_type', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('failure_screenshot', models.CharField(blank=True, max_length=1000)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
