# Generated by Django 5.2.17 on 2026-08-18 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_scraperrunlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable automatic scheduled scraper runs.')),
                ('interval_minutes', models.PositiveIntegerField(default=30, help_text='Minimum number of minutes between automatic runs.', validators=[django.core.validators.MinValueValidator(1)])),
                ('last_dispatched_at', models.DateTimeField(blank=True, editable=False, help_text='Last time an automatic scraper run was dispatched.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraper schedule',
                'verbose_name_plural': 'Scraper schedule',
            },
        ),
    ]
