# Generated by Django 5.2.17 on 2026-08-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_scraperschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
