# Generated by Django 5.2.17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_scraperrun_heartbeat_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScraperEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("run_started", "Run started"),
                            ("run_finished", "Run finished"),
                            ("run_failed", "Run failed"),
                            ("run_recovered", "Run recovered"),
                            ("subtype_started", "Subtype started"),
                            ("subtype_finished", "Subtype finished"),
                            ("subtype_retry", "Subtype retry"),
                            ("captcha_started", "CAPTCHA started"),
                            ("captcha_decision", "CAPTCHA decision"),
                            ("captcha_finished", "CAPTCHA finished"),
                            ("browser_started", "Browser started"),
                            ("browser_failed", "Browser failed"),
                            ("navigation_failed", "Navigation failed"),
                            ("appointment_detected", "Appointment detected"),
                            ("notification_sent", "Notification sent"),
                            ("notification_failed", "Notification failed"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("visa_sub_type", models.CharField(blank=True, db_index=True, max_length=255)),
                ("attempt_number", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=64)),
                ("reason_code", models.CharField(blank=True, db_index=True, max_length=128)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="operations.scraperrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["run", "created_at"], name="scraper_event_run_time_idx"),
                    models.Index(fields=["run", "event_type"], name="scraper_event_run_type_idx"),
                ],
            },
        ),
    ]
