# Generated by Django 5.2.17 on 2026-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_scraperevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('appointment_found', 'Appointment Found'), ('no_appointment', 'No Appointment'), ('server_error', 'Server Error'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
