# Generated by Django 5.2.17 on 2026-09-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_scraperrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperevent',
            name='event_type',
            field=models.CharField(choices=[('run_started', 'Run started'), ('run_finished', 'Run finished'), ('run_failed', 'Run failed'), ('run_recovered', 'Run recovered'), ('subtype_started', 'Subtype started'), ('subtype_finished', 'Subtype finished'), ('subtype_retry', 'Subtype retry'), ('captcha_started', 'CAPTCHA started'), ('captcha_decision', 'CAPTCHA decision'), ('captcha_finished', 'CAPTCHA finished'), ('browser_started', 'Browser started'), ('browser_failed', 'Browser failed'), ('navigation_failed', 'Navigation failed'), ('login_response', 'Login response'), ('appointment_detected', 'Appointment detected'), ('notification_sent', 'Notification sent'), ('notification_failed', 'Notification failed')], db_index=True, max_length=64),
        ),
    ]
