# Generated by Django 5.2.17 on 2026-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_scraperevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperrun',
            name='attempt_failures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='first_failure',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='terminal_failure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
