# Generated by Django 5.2.17 on 2026-09-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_scraperrun_attempt_failures_scraperrun_first_failure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperrun',
            name='stop_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraperrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stop_requested', 'Stop Requested'), ('stopped', 'Stopped'), ('appointment_found', 'Appointment Found'), ('no_appointment', 'No Appointment'), ('server_error', 'Server Error'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
