# Generated by Django 5.2.17 on 2026-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_scraperrun_stop_requested_at_scraperrun_stopped_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stop_requested', 'Stop Requested'), ('stopped', 'Stopped'), ('appointment_found', 'Appointment Found'), ('possible_appointment', 'Possible Appointment'), ('no_appointment', 'No Appointment'), ('server_error', 'Server Error'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
