# Generated by Django 5.2.17 on 2026-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_alter_scraperrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stop_requested', 'Stop Requested'), ('stopped', 'Stopped'), ('appointment_found', 'Appointment Found'), ('possible_appointment', 'Possible Appointment'), ('no_appointment', 'No Appointment Found'), ('server_error', 'Server Error'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
