# Generated by Django 5.2.17 on 2026-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_update_no_appointment_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyEndpointHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500, unique=True)),
                ('quarantined_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('consecutive_403', models.PositiveIntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_403_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy endpoint health',
                'verbose_name_plural': 'Proxy endpoint health',
                'ordering': ['endpoint'],
            },
        ),
    ]
