name: Deploy to Hamravesh

on:
  push:
    branches:
      - main

jobs:
  darkube_build_bls-scraper_safir-credit_hamravesh-c11:
    runs-on: ubuntu-latest
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root

    env:
      IMAGE_NAME: registry.hamdocker.ir/safir-credit/bls-scraper

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Darkube CLI build and push
        env:
          DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG }}
        run: |
          darkube build --push \
            -t "$IMAGE_NAME:${GITHUB_SHA:0:7}" \
            -t "$IMAGE_NAME:${GITHUB_REF_NAME}" \
            --docker-auth-config "$DOCKER_AUTH_CONFIG" \
            --workdir . \
            --file ./Dockerfile \
            --build-context .

  darkube_deploy_bls-scraper_safir-credit_hamravesh-c11:
    runs-on: ubuntu-latest
    container:
      image: hamravesh/darkube-cli:v1.1

    needs:
      - darkube_build_bls-scraper_safir-credit_hamravesh-c11

    steps:
      - name: Darkube CLI deploy
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN_BLS_SCRAPER_SAFIR_CREDIT_HAMRAVESH_C11 }}
          APP_ID: ${{ secrets.APP_ID_BLS_SCRAPER_SAFIR_CREDIT_HAMRAVESH_C11 }}
        run: |
          darkube deploy \
            --token "$DEPLOY_TOKEN" \
            --app-id "$APP_ID" \
            --image-tag "${GITHUB_SHA:0:7}" \
            --job-id "$GITHUB_RUN_ID"